# Codecov configuration for VaultStadio
# See https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "60..80"
  status:
    project:
      default:
        target: auto
        threshold: 1%
