/**
 * Spanish strings.
 */
package com.vaultstadio.app.core.resources

object SpanishStrings : StringResources {
    override val appName = "VaultStadio"

    override val navMyFiles = "Mis Archivos"
    override val navRecent = "Recientes"
    override val navStarred = "Destacados"
    override val navShared = "Compartidos"
    override val navSharedWithMe = "Compartidos Conmigo"
    override val navTrash = "Papelera"
    override val navSettings = "Ajustes"
    override val navProfile = "Perfil"
    override val navAdmin = "Administración"
    override val navPlugins = "Extensiones"
    override val navAI = "Asistente IA"
    override val navSync = "Sincronización"
    override val navFederation = "Federación"
    override val navCollaboration = "Colaboración"
    override val navActivity = "Actividad"
    override val navAdvanced = "Avanzado"

    override val actionNew = "Nuevo"
    override val actionUpload = "Subir"
    override val actionUploadFiles = "Subir Archivos"
    override val actionCreateFolder = "Crear Carpeta"
    override val actionSelectFiles = "Seleccionar Archivos"
    override val actionAddMoreFiles = "Añadir más archivos"
    override val actionCancel = "Cancelar"
    override val actionClose = "Cerrar"
    override val actionDone = "Hecho"
    override val actionSave = "Guardar"
    override val actionDelete = "Eliminar"
    override val actionRename = "Renombrar"
    override val actionMove = "Mover"
    override val actionCopy = "Copiar"
    override val actionShare = "Compartir"
    override val actionDownload = "Descargar"
    override val actionRestore = "Restaurar"
    override val actionEmptyTrash = "Vaciar Papelera"
    override val actionCopyLink = "Copiar Enlace"
    override val actionSearch = "Buscar archivos..."
    override val actionLogout = "Cerrar sesión"
    override val actionAdvancedSearch = "Búsqueda Avanzada"
    override val actionRefresh = "Actualizar"

    override val filesHome = "Inicio"
    override val filesEmpty = "Esta carpeta está vacía"
    override val filesSelectToUpload = "Selecciona archivos para subir"
    override val filesOfCompleted = "de %d completados"
    override val filesFailed = "(%d fallidos)"
    override val folderName = "Nombre de carpeta"
    override val folderNameError = "El nombre no puede estar vacío"
    override val folderNameSlashError = "El nombre no puede contener / o \\"

    override val authLogin = "Iniciar sesión"
    override val authRegister = "Registrarse"
    override val authEmail = "Correo electrónico"
    override val authPassword = "Contraseña"
    override val authUsername = "Nombre de usuario"
    override val authConfirmPassword = "Confirmar Contraseña"
    override val authForgotPassword = "¿Olvidaste tu contraseña?"
    override val authNoAccount = "¿No tienes cuenta?"
    override val authHaveAccount = "¿Ya tienes cuenta?"
    override val authWelcome = "Bienvenido de nuevo"
    override val authSignInToContinue = "Inicia sesión para continuar"
    override val authCreateAccount = "Crear cuenta"
    override val authJoinUs = "Únete a VaultStadio"

    override val settingsTitle = "Ajustes"
    override val settingsAppearance = "Apariencia"
    override val settingsTheme = "Tema"
    override val settingsThemeLight = "Claro"
    override val settingsThemeDark = "Oscuro"
    override val settingsThemeSystem = "Sistema"
    override val settingsLanguage = "Idioma"
    override val settingsStorage = "Almacenamiento"
    override val settingsStorageUsed = "%s de %s usado"
    override val settingsAccount = "Cuenta"
    override val settingsAbout = "Acerca de"
    override val settingsVersion = "Versión"

    override val shareTitle = "Compartir"
    override val shareCreateLink = "Crear Enlace"
    override val shareExpiration = "Expiración"
    override val sharePassword = "Contraseña"
    override val sharePasswordOptional = "Contraseña (opcional)"
    override val shareMaxDownloads = "Descargas máximas"
    override val shareUnlimited = "Ilimitado"
    override val shareDays = "días"
    override val shareNoShares = "Sin enlaces compartidos"
    override val shareNoSharesDesc = "Comparte archivos para verlos aquí"

    override val trashEmpty = "La papelera está vacía"
    override val trashEmptyDesc = "Los elementos eliminados aparecerán aquí"
    override val trashEmptyAction = "Vaciar Papelera"
    override val trashRestoreItem = "Restaurar"
    override val trashDeletePermanently = "Eliminar permanentemente"
    override val trashRestoreConfirmMessage = "¿Restaurar este elemento en su ubicación original?"
    override val trashDeletePermanentlyConfirmMessage =
        "Este elemento se eliminará de forma permanente. Esta acción no se puede deshacer."

    override val errorGeneric = "Algo salió mal"
    override val errorNetwork = "Error de red"
    override val errorAuth = "Error de autenticación"
    override val errorNotFound = "No encontrado"
    override val errorUpload = "Error al subir"

    override val timeJustNow = "Ahora mismo"
    override val timeMinuteAgo = "Hace 1 minuto"
    override val timeMinutesAgo = "Hace %d minutos"
    override val timeHourAgo = "Hace 1 hora"
    override val timeHoursAgo = "Hace %d horas"
    override val timeYesterday = "Ayer"
    override val timeDaysAgo = "Hace %d días"
    override val timeWeeksAgo = "Hace %d semanas"
    override val timeMonthsAgo = "Hace %d meses"
    override val timeYearsAgo = "Hace %d años"

    override val storageBytes = "B"
    override val storageKB = "KB"
    override val storageMB = "MB"
    override val storageGB = "GB"
    override val storageTB = "TB"
    override val storageFree = "libre"
    override val storageUsed = "usado"

    // AI
    override val aiAssistant = "Asistente IA"
    override val aiChat = "Chat"
    override val aiDescribe = "Describir"
    override val aiTag = "Etiquetar"
    override val aiClassify = "Clasificar"
    override val aiSummarize = "Resumir"
    override val aiProviders = "Proveedores IA"
    override val aiModels = "Modelos"
    override val aiNoProvider = "Sin proveedor IA configurado"
    override val aiConfigureProvider = "Configurar Proveedor"
    override val aiThinking = "Pensando..."
    override val aiSend = "Enviar"

    // Versioning
    override val versionHistory = "Historial de Versiones"
    override val versionRestore = "Restaurar"
    override val versionCompare = "Comparar"
    override val versionDownload = "Descargar"
    override val versionCleanup = "Limpiar"
    override val versionCurrent = "Actual"
    override val versionRestored = "Restaurado"
    override val versionNoHistory = "Sin historial de versiones"

    // Sync
    override val syncDevices = "Dispositivos"
    override val syncLastSync = "Última sincronización"
    override val syncConflicts = "Conflictos"
    override val syncResolve = "Resolver"
    override val syncDeactivate = "Desactivar"
    override val syncRemove = "Eliminar"
    override val syncNoDevices = "Sin dispositivos conectados"
    override val syncNoConflicts = "Sin conflictos"
    override val syncKeepLocal = "Mantener local"
    override val syncKeepRemote = "Mantener remoto"
    override val syncKeepBoth = "Mantener ambos"

    // Collaboration
    override val collaborationJoin = "Unirse"
    override val collaborationLeave = "Salir"
    override val collaborationParticipants = "Participantes"
    override val collaborationComments = "Comentarios"
    override val collaborationSave = "Guardar"
    override val collaborationResolve = "Resolver"
    override val collaborationReply = "Responder"
    override val collaborationNoComments = "Sin comentarios"

    // Federation
    override val federationInstances = "Instancias"
    override val federationRequest = "Solicitar Federación"
    override val federationShares = "Compartidos Federados"
    override val federationIdentities = "Identidades Vinculadas"
    override val federationActivities = "Actividades"
    override val federationBlock = "Bloquear"
    override val federationAccept = "Aceptar"
    override val federationDecline = "Rechazar"
    override val federationRevoke = "Revocar"
    override val federationNoInstances = "Sin instancias federadas"

    // Activity
    override val activityRecent = "Actividad Reciente"
    override val activityFilter = "Filtrar"
    override val activityNoActivity = "Sin actividad aún"

    // Metadata
    override val metadataDetails = "Detalles"
    override val metadataImage = "Detalles de Imagen"
    override val metadataVideo = "Detalles de Video"
    override val metadataDocument = "Detalles del Documento"
    override val metadataCamera = "Cámara"
    override val metadataLocation = "Ubicación"

    // Search
    override val searchAdvanced = "Búsqueda Avanzada"
    override val searchByContent = "Buscar en contenido"
    override val searchByMetadata = "Buscar por metadatos"
    override val searchFileType = "Tipo de Archivo"
    override val searchDateRange = "Rango de Fechas"
    override val searchSizeRange = "Rango de Tamaño"
    override val searchReset = "Restablecer"

    // Settings - Additional
    override val settingsAutoSync = "Sincronización Automática"
    override val settingsAutoSyncDesc = "Sincronizar archivos automáticamente"
    override val settingsClearCache = "Limpiar Caché"
    override val settingsClearCacheDesc = "Liberar espacio de almacenamiento"
    override val settingsNotifications = "Notificaciones"
    override val settingsPushNotifications = "Notificaciones Push"
    override val settingsPushNotificationsDesc = "Recibir notificaciones de subidas y compartidos"
    override val settingsSecurity = "Seguridad"
    override val settingsChangePassword = "Cambiar Contraseña"
    override val settingsChangePasswordDesc = "Actualizar tu contraseña"
    override val settingsLicenses = "Licencias"
    override val settingsLicensesDesc = "Licencias de código abierto"
    override val settingsSignOutDesc = "Cerrar sesión de tu cuenta"
    override val settingsLogoutConfirm = "¿Estás seguro de que quieres cerrar sesión?"

    // AI - Additional
    override val aiStartConversation = "Iniciar una Conversación"
    override val aiStartConversationDesc = "Pregúntame cualquier cosa sobre tus archivos " +
        "o pide ayuda con tareas"
    override val aiDescribeImage = "Describir una Imagen"
    override val aiDescribeImageDesc = "Pega una URL de imagen o sube una imagen " +
        "para obtener una descripción generada por IA"
    override val aiAutoTagContent = "Etiquetar Automáticamente"
    override val aiAutoTagContentDesc = "Sube una imagen o introduce texto " +
        "para generar etiquetas relevantes"
    override val aiSummarizeText = "Resumir Texto"
    override val aiSummarizeTextDesc = "Pega o escribe texto para obtener un resumen conciso"
    override val aiNoProviderConfigured = "Sin Proveedor IA Configurado"
    override val aiGeneratedTags = "Etiquetas Generadas"
    override val aiSelectModel = "Seleccionar Modelo"
    override val aiTypePlaceholder = "Escribe un mensaje..."
    override val aiImageUrlPlaceholder = "Pega URL de imagen o describe qué analizar…"
    override val aiTagPlaceholder = "Describe el contenido a etiquetar..."
    override val aiClassifyPlaceholder = "Introduce contenido a clasificar..."
    override val aiSummarizePlaceholder = "Pega texto a resumir..."
    override val aiCouldNotProcess = "Lo siento, no pude procesar esa solicitud."
    override val aiProvider = "Proveedor"

    // Federation - Additional
    override val federationTitle = "Federación"
    override val federationEnterDomain = "Introduce el dominio de la instancia VaultStadio con la que quieres federar."
    override val federationInstanceDomain = "Dominio de Instancia"
    override val federationInstanceDomainPlaceholder = "ej., vault.ejemplo.com"
    override val federationMessageOptional = "Mensaje (opcional)"
    override val federationBlockConfirm = "¿Estás seguro de que quieres bloquear esta instancia? " +
        "Esto impedirá cualquier comunicación con ella."
    override val federationNoSharesDesc = "Comparte archivos con otras instancias VaultStadio"
    override val federationIncomingShares = "Compartidos Entrantes"
    override val federationOutgoingShares = "Compartidos Salientes"
    override val federationNoLinkedIdentities = "Sin Identidades Vinculadas"
    override val federationLinkIdentityDesc = "Vincula tu identidad con instancias federadas"
    override val federationNoInstancesDesc = "Conecta con otras instancias VaultStadio " +
        "para compartir archivos entre organizaciones"

    // Collaboration - Additional
    override val collaborationJoiningSession = "Uniéndose a la sesión..."
    override val collaborationCouldNotJoin = "No se pudo unir a la sesión de colaboración"
    override val collaborationRetry = "Reintentar"
    override val collaborationAddComment = "Añadir Comentario"
    override val collaborationNoCommentsYet = "Sin comentarios aún"
    override val collaborationComment = "Comentario"
    override val collaborationAdd = "Añadir"
    override val collaborationVersion = "Versión"
    override val collaborationLastSaved = "Última vez guardado"
    override val collaborationSelectFileToStart = "Selecciona un archivo en Archivos para colaborar"

    // Sync - Additional
    override val syncTitle = "Sincronización y Dispositivos"
    override val syncDeactivateConfirm = "¿Estás seguro de que quieres desactivar este dispositivo? " +
        "Dejará de sincronizar hasta que se reactive."
    override val syncRemoveConfirm = "¿Estás seguro de que quieres eliminar este dispositivo? " +
        "Esta acción no se puede deshacer."
    override val syncResolveConflict = "Resolver Conflicto"
    override val syncChooseResolution = "Elige cómo resolver este conflicto:"
    override val syncKeepLocalVersion = "Mantener Versión Local"
    override val syncKeepRemoteVersion = "Mantener Versión Remota"
    override val syncKeepBothRename = "Mantener Ambas (renombrar una)"
    override val syncMergeChanges = "Combinar Cambios"
    override val syncResolveManually = "Resolver Manualmente"
    override val syncNoDevicesDesc = "Instala el cliente de sincronización en tus dispositivos " +
        "para mantener tus archivos sincronizados"
    override val syncAllInSync = "Todos tus archivos están sincronizados"
    override val syncInactive = "INACTIVO"

    // Version - Additional
    override val versionTitle = "Historial de Versiones"
    override val versionTotalSize = "Tamaño Total"
    override val versionVersions = "Versiones"
    override val versionRestoreConfirm = "Restaurar Versión"
    override val versionRestoreDesc = "Esto creará una nueva versión con el contenido de la versión %d."
    override val versionCommentOptional = "Comentario (opcional)"
    override val versionCleanupOld = "Limpiar Versiones Antiguas"
    override val versionCleanupDesc = "Eliminar versiones antiguas según los siguientes criterios:"
    override val versionKeepLast = "Mantener últimas N versiones"
    override val versionKeepLastPlaceholder = "ej., 10"
    override val versionDeleteOlderThan = "Eliminar versiones más antiguas de (días)"
    override val versionDeleteOlderThanPlaceholder = "ej., 30"

    // File Info - Additional
    override val infoType = "Tipo"
    override val infoFolder = "Carpeta"
    override val infoFile = "Archivo"
    override val infoSize = "Tamaño"
    override val infoMimeType = "Tipo MIME"
    override val infoUnknown = "Desconocido"
    override val infoCreated = "Creado"
    override val infoModified = "Modificado"
    override val infoPath = "Ruta"
    override val infoVisibility = "Visibilidad"
    override val infoMoveTo = "Mover a..."
    override val infoMakeCopy = "Hacer una copia"
    override val infoMoveToTrash = "Mover a papelera"

    // Common
    override val commonBack = "Atrás"
    override val commonRequest = "Solicitar"
    override val commonAccept = "Aceptar"
    override val commonDecline = "Rechazar"
    override val commonRevoke = "Revocar"
    override val commonBlock = "Bloquear"
    override val commonRemove = "Eliminar"
    override val commonDeactivate = "Desactivar"
    override val commonResolve = "Resolver"
    override val commonAdd = "Añadir"
    override val commonSend = "Enviar"
    override val commonRetry = "Reintentar"
    override val commonUnlink = "Desvincular"
    override val commonConfigure = "Configurar"
    override val commonSettings = "Configuración"
    override val commonPlay = "Reproducir"

    // Errors - Additional
    override val errorPasswordsDoNotMatch = "Las contraseñas no coinciden"
    override val errorEmailPasswordRequired = "El email y la contraseña son obligatorios"
    override val errorAllFieldsRequired = "Todos los campos son obligatorios"
    override val errorPasswordTooShort = "La contraseña debe tener al menos 8 caracteres"

    // Navigation - Additional
    override val navHome = "Inicio"
}
