/**
 * Shorthand access to common string resources.
 */

package com.vaultstadio.app.core.resources

val StringResources.files: String get() = navMyFiles
val StringResources.recent: String get() = navRecent
val StringResources.starred: String get() = navStarred
val StringResources.trash: String get() = navTrash
val StringResources.shared: String get() = navShared
val StringResources.sharedWithMe: String get() = navSharedWithMe
val StringResources.settings: String get() = navSettings
val StringResources.profile: String get() = navProfile
val StringResources.admin: String get() = navAdmin
val StringResources.plugins: String get() = navPlugins
val StringResources.ai: String get() = navAI
val StringResources.sync: String get() = navSync
val StringResources.federation: String get() = navFederation
val StringResources.collaboration: String get() = navCollaboration
val StringResources.activity: String get() = navActivity
val StringResources.advanced: String get() = navAdvanced
val StringResources.allFiles: String get() = filesHome
val StringResources.noFiles: String get() = filesEmpty
val StringResources.noRecentFiles: String get() = "No recent files"
val StringResources.noStarredFiles: String get() = "No starred files"
val StringResources.trashEmpty: String get() = trashEmptyDesc
val StringResources.emptyTrash: String get() = trashEmptyAction
val StringResources.newFolder: String get() = actionCreateFolder
val StringResources.folderName: String get() = folderName
val StringResources.create: String get() = actionSave
val StringResources.cancel: String get() = actionCancel
val StringResources.clear: String get() = actionClose
val StringResources.refresh: String get() = actionRefresh
val StringResources.selectAll: String get() = "Select All"
val StringResources.toggleView: String get() = "Toggle View"
val StringResources.move: String get() = actionMove
val StringResources.copy: String get() = actionCopy
val StringResources.delete: String get() = actionDelete
val StringResources.star: String get() = actionShare
val StringResources.clearSelection: String get() = actionClose
val StringResources.itemsSelected: String get() = "items selected"
val StringResources.rename: String get() = actionRename
val StringResources.newName: String get() = "New name"
val StringResources.moveToRoot: String get() = "Move this item to the root folder?"
val StringResources.moveHere: String get() = "Move Here"
val StringResources.copyToRoot: String get() = "Copy this item to the root folder?"
val StringResources.copyHere: String get() = "Copy Here"
val StringResources.share: String get() = shareTitle
val StringResources.shareDialogMessage: String get() = "Create a shareable link for this file:"
val StringResources.createLink: String get() = shareCreateLink
val StringResources.login: String get() = authLogin
val StringResources.register: String get() = authRegister
val StringResources.email: String get() = authEmail
val StringResources.password: String get() = authPassword
val StringResources.username: String get() = authUsername
val StringResources.confirmPassword: String get() = authConfirmPassword
val StringResources.alreadyHaveAccount: String get() = authHaveAccount
val StringResources.dontHaveAccount: String get() = authNoAccount
val StringResources.logout: String get() = actionLogout
val StringResources.sharing: String get() = shareTitle
val StringResources.myShares: String get() = navShared
val StringResources.noShares: String get() = shareNoShares
val StringResources.noSharedWithMe: String get() = "No files shared with you"
val StringResources.administration: String get() = navAdmin
val StringResources.noUsers: String get() = "No users"
val StringResources.noActivity: String get() = activityNoActivity
val StringResources.noPlugins: String get() = "No plugins installed"
val StringResources.noProfile: String get() = "No profile data"
val StringResources.darkMode: String get() = settingsThemeDark
val StringResources.language: String get() = settingsLanguage
val StringResources.searchPlaceholder: String get() = actionSearch
val StringResources.versionHistory: String get() = versionHistory
val StringResources.noVersionHistory: String get() = versionNoHistory
val StringResources.noAIProviders: String get() = aiNoProviderConfigured
val StringResources.noSyncDevices: String get() = syncNoDevices
val StringResources.noFederatedInstances: String get() = federationNoInstances
val StringResources.noActiveSession: String get() = "No active session"
